---
# tasks file for install-python
- name: install python packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - python 
  - python-setuptools 
  - python-dev 
  - build-essential 
  - python-pip 
  - python-mysqldb
