---
# tasks file for db
- name: install mysql
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - mysql-server
  - mysql-client

- name: start db
  service:
    name: mysql
    state: started
    enabled: yes

- name: create db
  mysql_db:
    name: employee_db
    state: present

- name: create db user
  mysql_user:
    name: db_user
    password: Passw0rd
    priv: "*.*:ALL"
    state: present
    host: "%"
